# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
pool:  
   name: local 

     
steps: 
- script: echo Hello, world! 
  displayName: 'Run a one-line script' 
   
- script:    pip3 install --upgrade pip3
  displayName: 'Run a one-line script' 
   
- script: |
    python -m pip3 install --upgrade pip
    pip3 install -r requirements.txt
  displayName: 'Install dependencies'
   
- script: |
    pip3 install pytest pytest-azurepipelines
    pytest
  displayName: 'run pytest'
